In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("ml_training_dataset.csv")

In [10]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 30000
Columns: 27

In [11]:
print(df.columns.tolist())

['Application_ID', 'Age', 'Gender', 'City', 'Employment_Type', 'Annual_Income', 'Employment_Duration_Years', 'Number_of_Dependents', 'Loan_Purpose', 'Loan_Amount', 'Loan_Tenure_Months', 'Existing_Loans_Count', 'Total_Outstanding_Debt', 'Existing_Monthly_EMI', 'Debt_to_Income_Ratio', 'Loan_to_Income_Ratio', 'Credit_Utilization', 'Previous_Defaults', 'Missed_Payments', 'Maximum_Days_Past_Due', 'Recent_Credit_Enquiries', 'Credit_History_Length', 'Number_of_Credit_Accounts', 'Payment_History', 'Credit_Score', 'Risk_Grade', 'Decision']

In [16]:
df.info()
df.head()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Application_ID             30000 non-null  int64
 1   Age                        30000 non-null  int64
 2   Gender                     30000 non-null  object
 3   City                       30000 non-null  object
 4   Employment_Type            30000 non-null  object
 5   Annual_Income              30000 non-null  int64
 6   Employment_Duration_Years  30000 non-null  float64
 7   Number_of_Dependents       30000 non-null  int64
 8   Loan_Purpose               30000 non-null  object
 9   Loan_Amount                30000 non-null  int64
 10  Loan_Tenure_Months         30000 non-null  int64
 11  Existing_Loans_Count       30000 non-null  int64
 12  Total_Outstanding_Debt     30000 non-null  float64
 13  Existing_Monthly_EMI       30000 non-null  float64
 14  Debt_to_Income_Ratio       30000 non-null  float64
 15  Loan_to_Income_Ratio       30000 non-null  float64
 16  Credit_Utilization         30000 non-null  float64
 17  Previous_Defaults          30000 non-null  int64
 18  Missed_Payments            30000 non-null  int64
 19  Maximum_Days_Past_Due      30000 non-null  int64
 20  Recent_Credit_Enquiries    30000 non-null  int64
 21  Credit_History_Length      30000 non-null  float64
 22  Number_of_Credit_Accounts  30000 non-null  int64
 23  Payment_History            30000 non-null  float64
 24  Credit_Score               30000 non-null  int64
 25  Risk_Grade                 30000 non-null  object
 26  Decision                   30000 non-null  object
dtypes: float64(8), int64(13), object(6)
memory usage: 6.2+ MB

,Application_ID,Age,Annual_Income,Employment_Duration_Years,Number_of_Dependents,Loan_Amount,Loan_Tenure_Months,Existing_Loans_Count,Total_Outstanding_Debt,Existing_Monthly_EMI,...,Loan_to_Income_Ratio,Credit_Utilization,Previous_Defaults,Missed_Payments,Maximum_Days_Past_Due,Recent_Credit_Enquiries,Credit_History_Length,Number_of_Credit_Accounts,Payment_History,Credit_Score
count,3.000000e+04,30000.000000,3.000000e+04,30000.000000,30000.000000,3.000000e+04,30000.000000,30000.000000,3.000000e+04,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,3.015000e+06,36.048000,7.283103e+05,5.590333,1.589733,1.103774e+06,46.539600,0.910600,2.533139e+05,7594.149667,...,151.937148,31.903810,0.160467,0.944900,10.885800,2.410200,12.428433,3.914200,95.694776,689.028967
std,8.660398e+03,8.207664,3.668370e+05,3.029603,1.253821,8.021058e+05,19.795441,1.035942,4.283075e+05,13138.868543,...,73.519671,16.281996,0.400902,1.142617,14.150532,1.657577,8.437444,1.749745,5.571274,46.201007
min,3.000001e+06,21.000000,1.800000e+05,0.500000,0.000000,5.000000e+04,12.000000,0.000000,0.000000e+00,0.000000,...,24.970000,1.000000,0.000000,0.000000,0.000000,0.000000,0.500000,1.000000,46.770000,497.000000
25%,3.007501e+06,30.000000,4.712750e+05,3.400000,1.000000,5.110000e+05,36.000000,0.000000,0.000000e+00,0.000000,...,88.540000,19.410000,0.000000,0.000000,0.000000,1.000000,5.600000,3.000000,94.110000,658.000000
50%,3.015000e+06,36.000000,6.529000e+05,5.500000,1.000000,9.190000e+05,48.000000,1.000000,5.880000e+04,1660.000000,...,151.385000,30.030000,0.000000,1.000000,8.000000,2.000000,11.900000,4.000000,97.530000,689.000000
75%,3.022500e+06,42.000000,8.971000e+05,7.700000,2.000000,1.475000e+06,60.000000,2.000000,3.498250e+05,10390.000000,...,215.890000,42.620000,0.000000,1.000000,16.000000,3.000000,18.300000,5.000000,100.000000,720.000000
max,3.030000e+06,65.000000,4.628500e+06,18.500000,6.000000,5.000000e+06,84.000000,4.000000,5.817200e+06,227120.000000,...,280.090000,96.200000,3.000000,10.000000,153.000000,10.000000,35.000000,13.000000,100.000000,848.000000

In [17]:
missing_values = df.isnull().sum()

print(missing_values)

Application_ID               0
Age                          0
Gender                       0
City                         0
Employment_Type              0
Annual_Income                0
Employment_Duration_Years    0
Number_of_Dependents         0
Loan_Purpose                 0
Loan_Amount                  0
Loan_Tenure_Months           0
Existing_Loans_Count         0
Total_Outstanding_Debt       0
Existing_Monthly_EMI         0
Debt_to_Income_Ratio         0
Loan_to_Income_Ratio         0
Credit_Utilization           0
Previous_Defaults            0
Missed_Payments              0
Maximum_Days_Past_Due        0
Recent_Credit_Enquiries      0
Credit_History_Length        0
Number_of_Credit_Accounts    0
Payment_History              0
Credit_Score                 0
Risk_Grade                   0
Decision                     0
dtype: int64

In [18]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print(missing_percentage.sort_values(ascending=False))

Application_ID               0.0
Debt_to_Income_Ratio         0.0
Risk_Grade                   0.0
Credit_Score                 0.0
Payment_History              0.0
Number_of_Credit_Accounts    0.0
Credit_History_Length        0.0
Recent_Credit_Enquiries      0.0
Maximum_Days_Past_Due        0.0
Missed_Payments              0.0
Previous_Defaults            0.0
Credit_Utilization           0.0
Loan_to_Income_Ratio         0.0
Existing_Monthly_EMI         0.0
Age                          0.0
Total_Outstanding_Debt       0.0
Existing_Loans_Count         0.0
Loan_Tenure_Months           0.0
Loan_Amount                  0.0
Loan_Purpose                 0.0
Number_of_Dependents         0.0
Employment_Duration_Years    0.0
Annual_Income                0.0
Employment_Type              0.0
City                         0.0
Gender                       0.0
Decision                     0.0
dtype: float64

In [19]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [20]:
print("Duplicate Application IDs:",
      df["Application_ID"].duplicated().sum())

Duplicate Application IDs: 0

In [21]:
print(df["Decision"].value_counts())

Decision
Reject     18583
Approve    11417
Name: count, dtype: int64

In [22]:
df["Decision"] = (
    df["Decision"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [23]:
df["Decision"] = df["Decision"].map({
    "reject": 0,
    "approve": 1
})

In [24]:
print(df["Decision"].value_counts())

Decision
0    18583
1    11417
Name: count, dtype: int64

In [26]:
columns_to_remove = [
    "Application_ID",
    "City",
    "Gender",
    "Risk_Grade"
]

df_clean = df.drop(columns=columns_to_remove)

In [27]:
print(df_clean.columns.tolist())

['Age', 'Employment_Type', 'Annual_Income', 'Employment_Duration_Years', 'Number_of_Dependents', 'Loan_Purpose', 'Loan_Amount', 'Loan_Tenure_Months', 'Existing_Loans_Count', 'Total_Outstanding_Debt', 'Existing_Monthly_EMI', 'Debt_to_Income_Ratio', 'Loan_to_Income_Ratio', 'Credit_Utilization', 'Previous_Defaults', 'Missed_Payments', 'Maximum_Days_Past_Due', 'Recent_Credit_Enquiries', 'Credit_History_Length', 'Number_of_Credit_Accounts', 'Payment_History', 'Credit_Score', 'Decision']

In [29]:
df_clean

,Age,Employment_Type,Annual_Income,Employment_Duration_Years,Number_of_Dependents,Loan_Purpose,Loan_Amount,Loan_Tenure_Months,Existing_Loans_Count,Total_Outstanding_Debt,...,Credit_Utilization,Previous_Defaults,Missed_Payments,Maximum_Days_Past_Due,Recent_Credit_Enquiries,Credit_History_Length,Number_of_Credit_Accounts,Payment_History,Credit_Score,Decision
0,21,Business Owner,631600,8.0,3,Home Renovation,263000,48,0,0.0,...,23.16,1,2,23,3,0.5,2,86.16,637,0
1,29,Business Owner,644100,10.9,3,Medical,651000,48,1,112300.0,...,27.53,0,0,0,1,7.7,3,100.00,698,1
2,28,Salaried,1018600,9.5,1,Personal,913000,36,0,0.0,...,31.55,0,0,0,3,2.3,3,100.00,677,1
3,30,Contract,901600,8.1,3,Medical,856000,48,2,739800.0,...,18.79,0,0,0,0,4.3,4,99.66,699,0
4,39,Salaried,1270100,6.3,0,Personal,463000,36,0,0.0,...,40.82,0,0,0,4,15.5,6,100.00,711,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Salaried,333000,12.3,0,Personal,427000,72,1,705600.0,...,6.57,0,1,10,2,0.5,5,94.69,647,0
29996,31,Professional,780500,7.7,3,Home,939000,36,2,1942000.0,...,3.64,0,1,14,0,7.1,4,93.95,719,0
29997,35,Salaried,687200,4.3,3,Personal,897000,36,0,0.0,...,53.55,0,1,13,1,11.0,3,92.64,659,0
29998,34,Self-Employed,348800,0.5,4,Vehicle,382000,24,0,0.0,...,20.76,0,1,10,4,5.8,3,97.24,682,0
29999,31,Salaried,345900,1.6,3,Personal,101000,72,2,481600.0,...,63.82,0,1,11,1,5.8,4,97.35,607,0

In [30]:
print(df_clean.dtypes)

Age                            int64
Employment_Type               object
Annual_Income                  int64
Employment_Duration_Years    float64
Number_of_Dependents           int64
Loan_Purpose                  object
Loan_Amount                    int64
Loan_Tenure_Months             int64
Existing_Loans_Count           int64
Total_Outstanding_Debt       float64
Existing_Monthly_EMI         float64
Debt_to_Income_Ratio         float64
Loan_to_Income_Ratio         float64
Credit_Utilization           float64
Previous_Defaults              int64
Missed_Payments                int64
Maximum_Days_Past_Due          int64
Recent_Credit_Enquiries        int64
Credit_History_Length        float64
Number_of_Credit_Accounts      int64
Payment_History              float64
Credit_Score                   int64
Decision                       int64
dtype: object

In [31]:
categorical_columns = df_clean.select_dtypes(
    include=["object"]
).columns.tolist()

print("Categorical columns:")
print(categorical_columns)

Categorical columns:
['Employment_Type', 'Loan_Purpose']

In [32]:
numerical_columns = df_clean.select_dtypes(
    exclude=["object"]
).columns.tolist()

print("Numerical columns:")
print(numerical_columns)

Numerical columns:
['Age', 'Annual_Income', 'Employment_Duration_Years', 'Number_of_Dependents', 'Loan_Amount', 'Loan_Tenure_Months', 'Existing_Loans_Count', 'Total_Outstanding_Debt', 'Existing_Monthly_EMI', 'Debt_to_Income_Ratio', 'Loan_to_Income_Ratio', 'Credit_Utilization', 'Previous_Defaults', 'Missed_Payments', 'Maximum_Days_Past_Due', 'Recent_Credit_Enquiries', 'Credit_History_Length', 'Number_of_Credit_Accounts', 'Payment_History', 'Credit_Score', 'Decision']

In [33]:
print("Final shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isnull().sum().sum())

print("\nDuplicate rows:")
print(df_clean.duplicated().sum())

Final shape: (30000, 23)

Missing values:
0

Duplicate rows:
0

In [34]:
df_clean.to_csv(
    "credit_dataset_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.