In [2]:
import pandas as pd
import joblib

In [3]:
model = joblib.load(
    "../models/logistic_regression_model.pkl"
)

print("Model loaded successfully.")

Model loaded successfully.

In [4]:
df = pd.read_csv("../data/credit_dataset_cleaned.csv")

print("Dataset shape:", df.shape)

Dataset shape: (30000, 23)

In [5]:
features = [
    "Age",
    "Employment_Type",
    "Annual_Income",
    "Employment_Duration_Years",
    "Number_of_Dependents",
    "Loan_Purpose",
    "Loan_Amount",
    "Loan_Tenure_Months",
    "Existing_Loans_Count",
    "Total_Outstanding_Debt",
    "Existing_Monthly_EMI",
    "Debt_to_Income_Ratio",
    "Loan_to_Income_Ratio",
    "Credit_Utilization",
    "Previous_Defaults",
    "Missed_Payments",
    "Maximum_Days_Past_Due",
    "Recent_Credit_Enquiries",
    "Credit_History_Length",
    "Number_of_Credit_Accounts",
    "Payment_History",
    "Credit_Score"
]

X = df[features]

In [6]:
probabilities = model.predict_proba(X)

reject_probability = probabilities[:, 0]
approve_probability = probabilities[:, 1]

In [7]:
probability_df = pd.DataFrame({
    "Reject_Probability": reject_probability,
    "Approve_Probability": approve_probability
})

probability_df.head(10)

   Reject_Probability  Approve_Probability
0            0.591603             0.408397
1            0.324405             0.675595
2            0.379860             0.620140
3            0.360004             0.639996
4            0.095533             0.904467
5            0.932719             0.067281
6            0.449793             0.550207
7            0.872383             0.127617
8            0.619279             0.380721
9            0.171006             0.828994

In [8]:
probability_df["Reject_Probability"] = (
    probability_df["Reject_Probability"] * 100
).round(2)

probability_df["Approve_Probability"] = (
    probability_df["Approve_Probability"] * 100
).round(2)

probability_df.head(10)

   Reject_Probability  Approve_Probability
0               59.16                40.84
1               32.44                67.56
2               37.99                62.01
3               36.00                64.00
4                9.55                90.45
5               93.27                 6.73
6               44.98                55.02
7               87.24                12.76
8               61.93                38.07
9               17.10                82.90

In [9]:
predicted_decision = model.predict(X)

In [10]:
probability_df["Predicted_Decision"] = predicted_decision

In [11]:
probability_df.head(10)

   Reject_Probability  Approve_Probability  Predicted_Decision
0               59.16                40.84                   0
1               32.44                67.56                   1
2               37.99                62.01                   1
3               36.00                64.00                   1
4                9.55                90.45                   1
5               93.27                 6.73                   0
6               44.98                55.02                   1
7               87.24                12.76                   0
8               61.93                38.07                   0
9               17.10                82.90                   1

In [12]:
probability_df["Probability_Sum"] = (
    probability_df["Reject_Probability"] +
    probability_df["Approve_Probability"]
).round(2)

probability_df.head(10)

,Reject_Probability,Approve_Probability,Predicted_Decision,Probability_Sum
0,59.16,40.84,0,100.0
1,32.44,67.56,1,100.0
2,37.99,62.01,1,100.0
3,36.00,64.00,1,100.0
4,9.55,90.45,1,100.0
5,93.27,6.73,0,100.0
6,44.98,55.02,1,100.0
7,87.24,12.76,0,100.0
8,61.93,38.07,0,100.0
9,17.10,82.90,1,100.0

In [13]:
print(
    "All probabilities sum to 100%:",
    (probability_df["Probability_Sum"] == 100.0).all()
)

All probabilities sum to 100%: True